name: De Tussenruimte
favicon: null
layout_spectrum: 0.966564666479826
typography_spectrum: 0.871561317704618
title: Bewust worden en kiezen
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#c1baa0'
    - '#000000'
    - '#392727'
    - '#c45c25'
  brandStrength: 0.5
  lightness: 0.1198920146562159
  saturation: 0.7553484700620174
  rhythmicContrast: 0.37177211279049516
purpose: []
